import { Schema, model, Document, Types } from 'mongoose';

export interface IVisitCompletionImage {
  type: 'shop' | 'selfie';
  url: string;
}

/** Optional extra shop photo a rider may add after checking out. */
export interface IVisitGalleryImage {
  url: string;
  caption?: string;
}

export interface IVisit extends Document {
  _id: Types.ObjectId;
  dealerId: Types.ObjectId;
  employeeId: Types.ObjectId;
  routeId?: Types.ObjectId;
  visitDate?: Date;
  status: 'todo' | 'in_progress' | 'checked_in' | 'completed' | 'skipped' | 'incomplete' | 'cancelled';
  checkedInAt?: Date;
  checkedInLatitude?: number;
  checkedInLongitude?: number;
  /** Set when a rider deliberately skips a visit on their route. */
  skippedAt?: Date;
  skipReason?: string;
  skippedBy?: Types.ObjectId;
  /**
   * True when the rider started this visit themselves from the client list, rather than
   * it being generated by the route cron or assigned by an admin.
   *
   * Missing/false means "assigned work" — which is correct for every pre-existing visit.
   * Extras are excluded from the 75% adherence rule (they would otherwise let a rider
   * pad away skipped route visits) but count fully as completed work in analytics.
   */
  isSelfInitiated?: boolean;
  /** Checkout time — set when the rider completes the visit. */
  completedAt?: Date;
  /** Minutes between check-in and checkout. Null/undefined when never checked in. */
  durationMinutes?: number;
  /** True when the stay exceeded VISIT_DURATION_LIMIT_MINUTES; surfaced to admins. */
  overstayFlagged?: boolean;
  latitude?: number;
  longitude?: number;
  completionImages?: IVisitCompletionImage[];
  /** Optional extra shop photos added by the rider after checkout. */
  galleryImages?: IVisitGalleryImage[];
  /** Optional free-text notes about the shop, added by the rider after checkout. */
  visitNotes?: string;
  galleryUpdatedAt?: Date;
  isTrashed?: boolean;
  trashedAt?: Date;
  trashedBy?: Types.ObjectId;
  createdBy?: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const visitCompletionImageSchema = new Schema<IVisitCompletionImage>(
  {
    type: { type: String, enum: ['shop', 'selfie'], required: true },
    url: { type: String, required: true },
  },
  { _id: false },
);

const visitGalleryImageSchema = new Schema<IVisitGalleryImage>(
  {
    url: { type: String, required: true },
    caption: { type: String, trim: true },
  },
  { _id: false },
);

const visitSchema = new Schema<IVisit>(
  {
    dealerId: { type: Schema.Types.ObjectId, ref: 'Dealer', required: true },
    employeeId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    routeId: { type: Schema.Types.ObjectId, ref: 'Route' },
    visitDate: { type: Date },
    status: {
      type: String,
      enum: ['todo', 'in_progress', 'checked_in', 'completed', 'skipped', 'incomplete', 'cancelled'],
      default: 'todo',
    },
    skippedAt: { type: Date },
    skipReason: { type: String, trim: true, maxlength: 300 },
    skippedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    isSelfInitiated: { type: Boolean, default: false },
    checkedInAt: { type: Date },
    checkedInLatitude: { type: Number },
    checkedInLongitude: { type: Number },
    completedAt: { type: Date },
    durationMinutes: { type: Number },
    overstayFlagged: { type: Boolean, default: false },
    latitude: { type: Number },
    longitude: { type: Number },
    completionImages: { type: [visitCompletionImageSchema], default: [] },
    galleryImages: { type: [visitGalleryImageSchema], default: [] },
    visitNotes: { type: String, trim: true },
    galleryUpdatedAt: { type: Date },
    isTrashed: { type: Boolean, default: false, index: true },
    trashedAt: { type: Date },
    trashedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true },
);

visitSchema.index({ dealerId: 1 });
visitSchema.index({ employeeId: 1 });
visitSchema.index({ routeId: 1 });
visitSchema.index({ status: 1 });
visitSchema.index({ isTrashed: 1, createdAt: -1 });
visitSchema.index({ isTrashed: 1, trashedAt: -1 });
// Admin review of riders who overstayed the allowed time at a store
visitSchema.index({ overstayFlagged: 1, isTrashed: 1, completedAt: -1 });
// Shop photo gallery lookups (all gallery entries for one dealer, newest first)
visitSchema.index({ dealerId: 1, galleryUpdatedAt: -1 });
// "Last visit" on the client profile — newest completed checkout for one dealer
visitSchema.index({ dealerId: 1, status: 1, completedAt: -1 });
// Analytics buckets a rider's visits by scheduled day, falling back to createdAt when the
// visit was not generated by the route cron. Both branches of that $or need their own
// index, or the monthly report degrades into a scan of the rider's entire visit history.
visitSchema.index({ employeeId: 1, visitDate: 1 });
visitSchema.index({ employeeId: 1, createdAt: 1 });
// The admin calendar and day views ask for a date window with no employee filter, so
// nothing above bounds them. visitDate leads because the range is what makes the scan
// small; `isTrashed` only filters within it and is not selective enough to lead.
visitSchema.index({ visitDate: -1, isTrashed: 1 });

export const VisitModel = model<IVisit>('Visit', visitSchema);
